spring.application.name=notas-fiscais

server.port=8082
pedido.api.base-url=http://localhost:8080

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=senha123

spring.rabbitmq.listener.simple.prefetch=1